import type { Metadata } from 'next';
import '../globals.css';
import Header from './_components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main className="flex-1 flex justify-center items-center">
        {children}
      </main>
    </>
  );
}
